name: Binary Size Analysis

on:
  issue_comment:
    types: [created, edited]

jobs:
  setup-toolchain:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/test-size') }}
    runs-on: ubuntu-latest
    steps:
      - name: Install RISC-V toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          target: riscv32imac-unknown-none-elf,riscv32imc-unknown-none-elf
          toolchain: stable
          components: rust-src, llvm-tools

      - name: Install Xtensa toolchain
        uses: esp-rs/xtensa-toolchain@v1.6
        with:
          version: 1.90.0.0

      - name: Install cargo-binutils
        run: cargo install cargo-binutils

  sleep-timer-esp32:
    needs: setup-toolchain
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/test-size') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.issue.pull_request.head.sha }}
          fetch-depth: 0

      - name: Build and get size
        working-directory: ./qa-test
        run: |
          cargo build --release --bin sleep_timer --features esp32 --target xtensa-esp32-espidf
          echo "=== ESP32 - Sleep Timer ==="
          cargo size --bin sleep_timer --release --features esp32 --target xtensa-esp32-espidf

  sleep-timer-esp32c3:
    needs: setup-toolchain
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/test-size') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.issue.pull_request.head.sha }}
          fetch-depth: 0

      - name: Build and get size
        working-directory: ./qa-test
        run: |
          cargo build --release --bin sleep_timer --features esp32c3 --target riscv32imc-unknown-none-elf
          echo "=== ESP32C3 - Sleep Timer ==="
          cargo size --bin sleep_timer --release --features esp32c3 --target riscv32imc-unknown-none-elf

  sleep-timer-esp32c6:
    needs: setup-toolchain
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/test-size') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.issue.pull_request.head.sha }}
          fetch-depth: 0

      - name: Build and get size
        working-directory: ./qa-test
        run: |
          cargo build --release --bin sleep_timer --features esp32c6 --target riscv32imac-unknown-none-elf
          echo "=== ESP32C6 - Sleep Timer ==="
          cargo size --bin sleep_timer --release --features esp32c6 --target riscv32imac-unknown-none-elf

  embassy-dhcp-esp32:
    needs: setup-toolchain
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/test-size') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.issue.pull_request.head.sha }}
          fetch-depth: 0

      - name: Build and get size
        working-directory: ./examples/wifi/embassy_dhcp
        run: |
          cargo build --release --features esp32 --target xtensa-esp32-espidf
          echo "=== ESP32 - Embassy DHCP ==="
          cargo size --release --features esp32 --target xtensa-esp32-espidf

  embassy-dhcp-esp32c3:
    needs: setup-toolchain
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/test-size') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.issue.pull_request.head.sha }}
          fetch-depth: 0

      - name: Build and get size
        working-directory: ./examples/wifi/embassy_dhcp
        run: |
          cargo build --release --features esp32c3 --target riscv32imc-unknown-none-elf
          echo "=== ESP32C3 - Embassy DHCP ==="
          cargo size --release --features esp32c3 --target riscv32imc-unknown-none-elf

  embassy-dhcp-esp32c6:
    needs: setup-toolchain
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/test-size') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.issue.pull_request.head.sha }}
          fetch-depth: 0

      - name: Build and get size
        working-directory: ./examples/wifi/embassy_dhcp
        run: |
          cargo build --release --features esp32c6 --target riscv32imac-unknown-none-elf
          echo "=== ESP32C6 - Embassy DHCP ==="
          cargo size --release --features esp32c6 --target riscv32imac-unknown-none-elf

  report-results:
    needs: [sleep-timer-esp32, sleep-timer-esp32c3, sleep-timer-esp32c6, embassy-dhcp-esp32, embassy-dhcp-esp32c3, embassy-dhcp-esp32c6]
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/test-size') }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Add PR comment
        continue-on-error: true
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## Binary Size Analysis ✅\n\nAll 6 builds completed successfully! Check the workflow run for detailed size outputs.`
            });