name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled, ready_for_review]

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  calculate:
    runs-on: ubuntu-latest
    steps:
      - name: Stand in for the long esp-hal build
        run: sleep 1800
